### PR TITLE
Improve docker-build

### PR DESCRIPTION
**Pull request by dashohoxha**

### CODE REVIEW

**Comment by dashohoxha** [comment]
It still fails at: `mysql -p < ....`

Maybe this can help: http://www.microhowto.info/howto/perform_an_unattended_installation_of_a_debian_package.html

**Comment by pparent76** [comment]
If the mysql password request is a problem we can change the way it is done. 
It is in the Own-Mailbox_local_postfix_conf repository.

**Comment by dashohoxha** [comment]
It is one of the problems, because the docker installation is done non-interactively, so it cannot get a password from the user.

Consider making these improvements as well:

```
diff --git a/cleanup.sh b/cleanup.sh
index 052cee9..32d5349 100755
--- a/cleanup.sh
+++ b/cleanup.sh
@@ -1,3 +1,3 @@
 #!/bin/bash

-rm /etc/omb/*
+rm -rf /etc/omb/*
diff --git a/debian-jessie b/debian-jessie
index c25a627..f0e4678 100644
--- a/debian-jessie
+++ b/debian-jessie
@@ -4,5 +4,6 @@ RUN apt-get update; apt-get -y upgrade
 RUN apt-get -y install git

 COPY . /own-mailbox/
-RUN cd /own-mailbox/ ; \
-    DEBIAN_FRONTEND=noninteractive ./main.sh
+RUN DEBIAN_FRONTEND=noninteractive /own-mailbox/cleanup.sh
+RUN DEBIAN_FRONTEND=noninteractive /own-mailbox/required_packages.sh
+RUN DEBIAN_FRONTEND=noninteractive /own-mailbox/main.sh
```

**Comment by dashohoxha** [comment]
This fix is needed too:
https://github.com/dashohoxha/Own-Mailbox_debian_install/commit/7b4d76a734c14e64fab0bd423c37ba29f5e91771

**Comment by pparent76** [comment]
Do you know what is the root mysql password when installing mysql in non interactive mode? Is it then possible to connect to mysql in root without the -p option?

**Comment by pparent76** [comment]
I think the best would be to make main.sh non-interactive by default, it would avoid problems and hassles.

**Comment by dashohoxha** [comment]
> Do you know what is the root mysql password when installing mysql in non interactive mode?

Maybe empty, no-password. You can try it.

**Comment by dashohoxha** [comment]
However you can also use:

```
mysql --defaults-file=/etc/mysql/debian.cnf .....
```

It will work whatever is the password. For example I use it here: https://github.com/B-Translator/btr_server/blob/master/install/config/set_mysql_passwd.sh

**Comment by pparent76** [comment]
Ok great!
Should work now!

**Comment by pparent76** [comment]
Though in docker services (apache2, postfix, rc.local ect..) does not seem to launch automatically. (I need to launch them by hand). Is it normal?

**Comment by pparent76** [comment]
Also one problem with docker as is that it does not take into account iptables. 
We would need to be able to run the image in a real virtual machine with a separated kernel, to do full-fledge testing.

**Comment by dashohoxha** [comment]
> Though in docker services (apache2, postfix, rc.local ect..) does not seem to launch automatically. (I need to launch them by hand). Is it normal?

Usually this is considered normal in docker. But if you use `/sbin/init` as the command of the container, it should be able to start all the services.
Example: https://github.com/docker-build/bind9/blob/master/run.sh#L21

In `ubuntu:14.04` this was a problem. But the image `ubuntu-upstart:14.04` fixes exactly this.
Example: https://github.com/docker-build/bind9/blob/master/Dockerfile#L1
In `ubuntu:16.04` it is again a problem and I don't know any fix yet.
In debian I don't remember having any problems with it, but maybe I have tried `debian:7`, not `debian:8`.

> Also one problem with docker as is that it does not take into account iptables. 

This can be fixed by adding the capability NET_ADMIN, like this:
https://github.com/docker-build/bind9/blob/master/run.sh#L19
Or you can make the container proviledged, like this:
https://github.com/pparent76/Own-Mailbox_debian_install/blob/master/docker.sh#L54
Making a container priviledged gives the container full access to the host system, so you should be carefull with it. For example `reboot` usually does nothing on a docker container, but if it is priviledged it will reboot the host system.

> We would need to be able to run the image in a real virtual machine with a separated kernel, to do full-fledge testing.

This is true. But usually a docker container is more restricted than a real VM, and if all testing goes well on it, it should work on a real VM (or a real machine) as well. However there may be a few things that do not work on docker, but work on a real VM.

**Pull request merged**
